---
- hosts: all
  gather_facts: yes

  tasks:
    - name: Set IP facts
      set_fact:
        www_main_ip: "{{ hostvars[groups['www'][0]].ansible_all_ipv4_addresses[0] }}"
        www_internal_ip: "{{ hostvars[groups['www'][0]].ansible_all_ipv4_addresses[1] }}"
        db_main_ip: "{{ hostvars[groups['db'][0]].ansible_all_ipv4_addresses[0] }}"
        db_internal_ip: "{{ hostvars[groups['db'][0]].ansible_all_ipv4_addresses[1] }}"
      tags: always

- import_playbook: playbooks/db/main.yml
- import_playbook: playbooks/www/main.yml
