---
- hosts: www
  become: yes

  vars_files:
    - vars.yml
    - ../../vars.yml

  pre_tasks:

  roles:
    - { role: noplanman.apt-extra-sources, tags: apt-extra-sources }
    - { role: geerlingguy.git, tags: git }
    - { role: geerlingguy.firewall, tags: firewall }
    - { role: geerlingguy.security, tags: security }
    # dhparam MUST come before nginx!
    - { role: noplanman.dhparam, tags: dhparam }
    - { role: geerlingguy.nginx, tags: nginx }
    # - { role: geerlingguy.memcached, tags: memcached }
    - { role: geerlingguy.php, tags: php }
    - { role: geerlingguy.composer, tags: composer }
    - { role: geerlingguy.php-mysql, tags: php-mysql }
    # - { role: geerlingguy.php-memcached, tags: php-memcached }
