---
apt_extra_sources_nginx: yes
apt_extra_sources_php71: yes

firewall_allowed_tcp_ports:
  - 22
  - 443

php_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php7.1-opcache
  - php7.1-xml
  - php7.1-mbstring
  - php-apcu

php_mysql_package: php7.1-mysql

php_webserver_daemon: nginx
php_fpm_daemon: php7.1-fpm
php_fpm_conf_path: /etc/php/7.1/fpm
php_conf_paths:
  - /etc/php/7.1/cli
  - /etc/php/7.1/fpm
php_extension_conf_paths:
  - /etc/php/7.1/cli/conf.d
  - /etc/php/7.1/fpm/conf.d
php_date_timezone: "Etc/UTC"

nginx_server_tokens: "off"
nginx_remove_default_vhost: yes

nginx_conf_path: /etc/nginx/conf.d
nginx_default_vhost_path: "{{ nginx_conf_path }}/default.conf"

nginx_upstreams:
  - name: php-handler
    servers:
      - unix:/var/run/php/php7.1-fpm.sock

dhparam_size: 4096
dhparam_create_on_local_machine: yes
dhparam_periodic_update: monthly

nginx_extra_http_options: |
  ##
  # SSL Settings
  ##
  ssl_dhparam {{ dhparam_path }};
  ssl_prefer_server_ciphers on;
  ssl_protocols TLSv1.2;
  ssl_ciphers 'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS';
  ssl_ecdh_curve secp384r1;
  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off;
