---
- name: Check if DH param exists.
  stat:
    path: "{{ acme_dhparam_path }}"
  register: acme_dhparam_exists

- block:
  - name: Check openssl is installed on Ansible controller.
    shell: openssl version | awk '{print $2}'
    changed_when: false
    register: acme_dhparam_local_version
    become: no
    delegate_to: localhost

  - name: Assert that required software is installed.
    assert:
      that:
        - 'acme_dhparam_local_version is defined and acme_dhparam_local_version.stdout'
    become: no
    delegate_to: localhost

  - name: Create temporary file for dhparam.pem.
    tempfile:
      path: "{{ playbook_dir }}"
    register: acme_dhparam_tmp_dhparam_file
    changed_when: no
    become: no
    delegate_to: localhost

  - name: Generate Diffie-Hellman params on Ansible controller.
    command: openssl dhparam -out "{{ acme_dhparam_tmp_dhparam_file.path }}" {{ acme_dhparam_size }}
    become: no
    delegate_to: localhost

  - name: Copy Diffie-Hellman params to host.
    copy:
      src: "{{ acme_dhparam_tmp_dhparam_file.path }}"
      dest: "{{ acme_dhparam_path }}"
      owner: root
      group: root

  - name: Remove temporary file for dhparam.pem.
    file:
      path: "{{ acme_dhparam_tmp_dhparam_file.path }}"
      state: absent
    changed_when: no
    become: no
    delegate_to: localhost

  when: not acme_dhparam_exists.stat.exists and acme_dhparam_create_on_localhost

- block:
  - name: Ensure openssl is installed.
    apt:
      name: openssl

  # https://weakdh.org
  - name: Generate strong DHE parameter
    command: openssl dhparam -out {{ acme_dhparam_path }} {{ acme_dhparam_size }}

  when: not acme_dhparam_exists.stat.exists and not acme_dhparam_create_on_localhost
