---
- include_tasks: install.yml
  tags: acme:install
- include_tasks: scripts.yml
  tags: acme:scripts
- include_tasks: hpkp.yml
  tags: acme:hpkp
  when: acme_hpkp_enabled
- include_tasks: ocsp.yml
  tags: acme:ocsp
  when: acme_ocsp_enabled
- include_tasks: certs.yml
  tags: acme:certs
