---
- name: Ensure necessary APT packages are installed.
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - lsb-release
    - ca-certificates

- include: mariadb.yml
  when: extra_repos_mariadb
- include: nginx.yml
  when: extra_repos_nginx
- include: php71.yml
  when: extra_repos_php71
