---
# https://packages.sury.org/php/README.txt
- name: Ensure PHP 7.1 trusted GPG key is installed.
  get_url:
    url: "{{ extra_repos_php71_gpg_url }}"
    dest: /etc/apt/trusted.gpg.d/php.gpg

- name: Ensure PHP 7.1 APT repository list is installed.
  apt_repository:
    repo: "{{ extra_repos_php71_repo }}"
