---
- hosts: db
  become: yes

  vars_files:
    - vars.yml
    - ../../vars.yml

  pre_tasks:
    - name: Create dynamic MySQL variables.
      set_fact:
        mysql_users:
          - name: "{{ db_mysql_username }}"
            host: "{{ www_internal_ip }}"
            password: "{{ db_mysql_password }}"
            priv: "*.*:ALL"

  roles:
    - { role: ../../roles/extra-repos, tags: extra-repos }
    - { role: geerlingguy.firewall, tags: firewall }
    - { role: geerlingguy.security, tags: security }
    - { role: geerlingguy.mysql, tags: mysql }
