---
apt_extra_sources_nginx: yes
apt_extra_sources_php71: yes

firewall_allowed_tcp_ports:
  - 22
  - 443
# @todo: Remove when sudo user is created.
security_ssh_permit_root_login: "yes"

git_packages:
  - git

php_packages:
  - php7.1-common
  - php7.1-cli
  - php7.1-dev
  - php7.1-fpm
  - libpcre3-dev
  - php7.1-gd
  - php7.1-curl
  - php7.1-imap
  - php7.1-json
  - php7.1-opcache
  - php7.1-xml
  - php7.1-mbstring
  - php-apcu

php_mysql_package: php7.1-mysql

php_webserver_daemon: nginx
php_fpm_daemon: php7.1-fpm
php_fpm_conf_path: /etc/php/7.1/fpm
php_conf_paths:
  - /etc/php/7.1/cli
  - /etc/php/7.1/fpm
php_extension_conf_paths:
  - /etc/php/7.1/cli/conf.d
  - /etc/php/7.1/fpm/conf.d

nginx_server_tokens: "off"
nginx_remove_default_vhost: yes

nginx_upstreams:
  - name: php-handler
    servers:
      - unix:/var/run/php/php7.1-fpm.sock
